### ISSUE TITLE
Type mismatch: inferred type is ReadableMap? but ReadableMap was expected

### ISSUE THREAD

**Issue by prashanthacharyam** [react-native-menu/menu#146]
yarn run android throw below error 

e: /app/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (141, 38): Type mismatch: inferred type is ReadableMap? but ReadableMap was expected
e: /app/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (177, 34): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: /app/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (177, 64): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: /app/node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (181, 35): Type mismatch: inferred type is ReadableMap? but ReadableMap was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-menu_menu:compileDebugKotlin'.
> Compilation error. See log for more details

I am using the latest version.

**Comment by mateusz1913** [comment]
Hi @prashanthacharyam , which version of react-native do you use?

**Comment by prashanthacharyam** [comment]
React native version 0.63

**Comment by enerve** [comment]
I got this identical error as well.... failed when building android...
`Execution failed for task ':react-native-menu_menu:compileDebugKotlin'`

I just installed react-native-menu today. version 0.4.1
React native version 0.63.4
