### ISSUE TITLE
Build crashes on android

### ISSUE THREAD

**Issue by MauriceNino** [react-native-menu/menu#179]
Hi there!

When I build the project, I get the following errors:

```
e: /.../node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (196, 56): Unresolved reference: Q
e: /.../node_modules/@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt: (197, 20): Unresolved reference: setForceShowIcon
```

After a bit of research in your code, I saw that you seemed to fix this with commit [#ad558f8e](https://github.com/react-native-menu/menu/commit/ad558f8e55c6bfeb68c4c27d70bbb4c6d010f6bb). Although, after installing that specific commit as a npm package and trying to build again, it still crashes with the same errors.

I checked my local files, and I am confident, that the properties are:

```
Menu_kotlinVersion=1.3.50
Menu_compileSdkVersion=29
Menu_buildToolsVersion=30.0.3
Menu_targetSdkVersion=29
```

Is there any fix, other than forking and commenting the lines that break the build?

**Comment by nagasai-tilicho** [comment]
I have also same issue.
is there any solution??

**Comment by MauriceNino** [comment]
The currently most downloaded version of this package (in the last 7 days) is `0.1.2` & we ended up using `0.2.0`. So if you are having issues, try downgrading to an older version.

**Comment by Naturalclar** [comment]
Should be fixed in the latest version :+1:
