### ISSUE TITLE
on iOS 13 only the first event is fired

### ISSUE THREAD

**Issue by Guuz** [react-native-menu/menu#236]
You can reproduce this by using the simplest form of this component with a few options (i have 3).
When i console.log `onPressAction` on iOS 14 and 15 everything is fine. It fires every thing i pick an option.
But on iOS 13 (simulator) only the first selection is fired and any others after that are not.
Only after leaving the screen (unmounting the component) and coming back it works again. But only once...

**Comment by JoniVR** [comment]
@Guuz If you want a workaround until the PR is merged + released, use patch-package with the patchfile provided in this zip:
[@react-native-menu+menu+0.5.1.patch.zip](https://github.com/react-native-menu/menu/files/7610117/%40react-native-menu%2Bmenu%2B0.5.1.patch.zip)
