### ISSUE TITLE
Menu not work in the touchableOpacity component

### ISSUE THREAD

**Issue by aldobel** [react-native-menu/menu#314]
Hello everyone, I would like to understand why when I insert the <MenuView> component inside an onLongPress of a <TouchableOpacity> component, the menu does not appear. What am I doing wrong? Is it incompatible? Thank you

**Comment by kayode0x** [comment]
Can you share the code you have?

**Comment by aldobel** [comment]
Sorry, but right now I can't show you the exact code, however it looks like this:
`
const componentOne = () =>{
       <ToachableOpacity onPressLong={()=>{menuHanlder()}>[code]</TouchableOpacity>
       }
       
const menuHandler = () => {
     <MenuView action={[…]} title=‘Menu’></MenuView>
}
`
the code is about this, but if you need the details later I try to provide it.  Thanks for the prompt reply.

**Comment by kayode0x** [comment]
Okay from what I know, your code won't work, you can try this mini example below.

<MenuView
     actions={[..actions]}
     shouldOpenOnLongPress={true}  //this is what you probably need.
>
     {...the component you want to add the menu on.  //eg [code]}
</MenuView>

The `MenuView` needs children passed into it, that way it knows what to render.

**Comment by aldobel** [comment]
Perfect, the problem was just that, that the <MenuView> component has to wrap all the other components. Now, however, on the iOS simulator it is fine, but on the android simulator it crashes. How come? Thanks for this beautiful component.

**Comment by kayode0x** [comment]
Glad it worked. You would need to share the error message you got, it's hard trying to figure out what it was.

**Comment by aldobel** [comment]
I would do it if you gave me any errors, of any kind.  Unfortunately, however, I don't get any errors when I try to bring up the menu on android (in long press mode), the app just closes.

**Comment by kayode0x** [comment]
Hmmm, are you running on expo or bare react native?

**Comment by aldobel** [comment]
I use ```yarn start``` command and start the project with expo, but I have eject expo, so, if the build isn’t on the simulator, I have to do ``` yarn iOS``` or ``` yarn android``` to create the builds and install them in the simulators / mobile phones

**Comment by aldobel** [comment]
So, with this post, I close the issue, in practice, I started the build with android studio, and they gave me the error, that is, the title was missing in a menu action, crashing the app. Thanks for the support

**Comment by kayode0x** [comment]
Oh yeah, you can pass an empty string "" if you don't want a title. Always happy to help.

**Comment by astriskit** [comment]
Came across this issue while searching on a similar issue; Adding here just in case.

Issue - On ios the TouchableOpacity's onPress won't trigger. The source tree: Menu->TouchableOpacity->Icon.

What solved the issue? Change of the elements' order: TouchableOpacity -> Menu -> Icon.
