### ISSUE TITLE
Explicitly define `children` as a prop for `MenuView`

### ISSUE THREAD

**Issue by BenJeau** [react-native-menu/menu#433]
Since React 18 `children` (which was introduced in React Native `0.69`) is not a part of `React.FC`. We should specify the need (or option) of a children here https://github.com/react-native-menu/menu/blob/master/src/index.tsx#L20. Here are some possible solutions https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc

This is the type error I have currently:
<img width="514" alt="Screen Shot 2022-09-20 at 5 30 50 PM" src="https://user-images.githubusercontent.com/22248828/191368446-59490f85-22c5-42af-bdc7-b28a5364501b.png">

**Comment by Naturalclar** [comment]
Fixed in v0.5.3 :tada:
