### ISSUE TITLE
🐞 Subtitle not showing on the Menu items

### ISSUE THREAD

**Issue by imransilvake** [react-native-menu/menu#536]
Problem:
The subtitle on iOS is not working. It doesn't do anything when I add the subtitle.

Usage
<img width="482" alt="245613564-56844843-6b42-454d-9da0-53db2c933281" src="https://github.com/react-native-menu/menu/assets/13087225/541d678e-b1a7-4116-8f0b-1f1819c11a25">

Menu
<img width="251" alt="245613715-b3546abe-9819-4f57-8471-653086fd21c5" src="https://github.com/react-native-menu/menu/assets/13087225/5d83cefb-bb80-4e57-878c-e2637530311a">

Platform: iOS
Versions:
```
"@react-native-menu/menu": "^0.8.0",
"react-native": "0.71.8",
"react": "18.2.0"
```

**Comment by illusion77** [comment]
Same issue

**Comment by shawarmaz** [comment]
Seeing this as well
