### ISSUE TITLE
Only safe (?.) or non-null asserted (!!.) calls are allowed on a null

### ISSUE THREAD

**Issue by romweb** [react-native-menu/menu#70]
I have build error in new ver 0.3.1:

![image](https://user-images.githubusercontent.com/8165380/112748617-8d7c6080-8fc5-11eb-9cfb-8366e504b8a3.png)

    ext {
        buildToolsVersion = '29.0.2'
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        kotlin_version = '1.3.50'
    }

**Comment by mateusz1913** [comment]
I guess that was fixed with #73. @Naturalclar ?

**Comment by Naturalclar** [comment]
@romweb thanks for raising the issue! This should be fixed on the latest version. Could you try it out?

**Comment by brentvatne** [comment]
this continues to be an issue on projects using kotlin 1.4+ :)
