### ISSUE TITLE
Compilation error on iOS with RN 0.74 and New Arch enabled

### ISSUE THREAD

**Issue by fobos531** [react-native-menu/menu#750]
Compiling the iOS example app with RN 0.74 and New arch enabled produces the following error for me:

![CleanShot 2024-04-12 at 18 32 40@2x](https://github.com/react-native-menu/menu/assets/19533289/6d380590-be4c-45fb-9d47-e78dfbcfe9fd)

**Comment by alanleedev** [comment]
It appears `#else` ~ `#endif` needs to be removed? Seem to work fine with code in the `#ifdef`.

**Comment by alanleedev** [comment]
@SudoPlz Could you verify if the above code can be deleted?
It seemed to have been added by you here: https://github.com/react-native-menu/menu/pull/682/files
`RN_FABRIC_ENABLED` is not defined anywhere and not use if `#else` is needed.

**Comment by fobos531** [comment]
True, it seems kinda redundant to have an #ifdef RN_FABRIC_ENABLED check if the whole file is specific to new architecture, or?

**Comment by alanleedev** [comment]
Could be a different issue but even if it builds, I noticed that the sub menu is broken on iOS with new architecture. All the top level and sub level menu appear together in a big popup.

**Comment by alanleedev** [comment]
Created a PR here: PR #767

**Comment by SudoPlz** [comment]
I can't remember off the top of my head why I added that code (I was trying a lot of things so it could be and oversight on my end), but if you can confirm that after removing that code that **taps continue to work** **when fabric is disabled**, then it's safe to remove.

**Comment by alanleedev** [comment]
> I can't remember off the top of my head why I added that code (I was trying a lot of things so it could be and oversight on my end), but if you can confirm that after removing that code that **taps continue to work** **when fabric is disabled**, then it's safe to remove.

@SudoPlz This change does not impact legacy architecture and it seems to work fine.

**Comment by Naturalclar** [comment]
made a release with this change in v1.0.1 🚀
