### ISSUE TITLE
Sub menu support

### ISSUE THREAD

**Issue by mateusz1913** [react-native-menu/menu#80]
Android `PopupMenu` widget supports adding one level nested sub menu (https://developer.android.com/reference/android/view/SubMenu)

iOS `UIMenu` (https://developer.apple.com/documentation/uikit/uimenu) supports `UIMenuElement` components as items. `UIMenu` is inheriting `UIMenuElement`, so it is possible to nest multiple levels of sub menus

**Comment by mateusz1913** [comment]
Hi @Naturalclar 👋, is there anything I need to fix here, in order to merge?

**Comment by Naturalclar** [comment]
@mateusz1913 merged and published v0.4.0, thanks so much!
