### ISSUE TITLE
Build fails for iOS on react-native@0.74.1 with newArchEnabled and useFrameworks = static

### ISSUE THREAD

**Issue by Kasendwa** [react-native-menu/menu#801]
Hi! First of all, thanks for the wonderful work on this package.

I have failed to make a build with `react-native@0.74.1`, `newArchEnabled = true` and `useFrameworks = "static"`

The error is as shown below

```
Compiling @react-native-menu/menu Pods/react-native-menu » MenuViewManager.mm
› Compiling @react-native-menu/menu Pods/react-native-menu » MenuView.mm

❌  (node_modules/@react-native-menu/menu/ios/NewArch/MenuView.mm:2:9)

  1 | #ifdef RCT_NEW_ARCH_ENABLED
> 2 | #import <react_native_menu-Swift.h>
    |         ^ 'react_native_menu-Swift.h' file not found
  3 | #import "MenuView.h"
  4 | 
  5 | #import <react/renderer/components/RNMenuViewSpec/ComponentDescriptors.h>

› Preparing react-native Pods/React-RCTImage » React-RCTImage-Info.plist
```

I am using `@react-native-menu/menu@1.0.2`

**Comment by Darren120** [comment]
solve?

**Comment by Kasendwa** [comment]
> solve?

Sorry, did I do something wrong? Or missed out something?

**Comment by Darren120** [comment]
> > solve?
> 
> Sorry, did I do something wrong? Or missed out something?

no i ask if u solve it

**Comment by Kasendwa** [comment]
> it

Oh. Not yet. But hopefully I will find a solution soon.

I will update here in case of anything

**Comment by rranjan14** [comment]
This patch solves it for me
```diff --git a/node_modules/@react-native-menu/menu/ios/NewArch/MenuView.mm b/node_modules/@react-native-menu/menu/ios/NewArch/MenuView.mm
index 6018cd1..23ef306 100644
--- a/node_modules/@react-native-menu/menu/ios/NewArch/MenuView.mm
+++ b/node_modules/@react-native-menu/menu/ios/NewArch/MenuView.mm
@@ -1,5 +1,5 @@
 #ifdef RCT_NEW_ARCH_ENABLED
-#import <react_native_menu-Swift.h>
+#import <react_native_menu/react_native_menu-Swift.h>
 #import "MenuView.h"
 
 #import <react/renderer/components/RNMenuViewSpec/ComponentDescriptors.h>
```

**Comment by francosion042** [comment]
@rranjan14 what verson of `react-native-menu` do you have?

**Comment by rranjan14** [comment]
> @rranjan14 what verson of `react-native-menu` do you have?

1.0.2

**Comment by francosion042** [comment]
> > @rranjan14 what verson of `react-native-menu` do you have?
> 
> 1.0.2

hmm, i've tried and it didn't work for me

**Comment by Kasendwa** [comment]
> This patch solves it for me
> 
> ```diff
> index 6018cd1..23ef306 100644
> --- a/node_modules/@react-native-menu/menu/ios/NewArch/MenuView.mm
> +++ b/node_modules/@react-native-menu/menu/ios/NewArch/MenuView.mm
> @@ -1,5 +1,5 @@
>  #ifdef RCT_NEW_ARCH_ENABLED
> -#import <react_native_menu-Swift.h>
> +#import <react_native_menu/react_native_menu-Swift.h>
>  #import "MenuView.h"
>  
>  #import <react/renderer/components/RNMenuViewSpec/ComponentDescriptors.h>
> ```

Lovely! This worked for me. Thanks a lot.

**Comment by JuanRdBO** [comment]
Can we please merge this to main? I'd love to import this library

**Comment by JuanRdBO** [comment]
I'm getting this error: 

<img width="587" alt="Screenshot 2024-05-11 at 13 55 15" src="https://github.com/react-native-menu/menu/assets/28183468/6107935a-6392-42ca-b5cf-3ec685b866d2">

**Comment by Kasendwa** [comment]
> I'm getting this error:
> 
> <img alt="Screenshot 2024-05-11 at 13 55 15" width="587" src="https://private-user-images.githubusercontent.com/28183468/329775890-6107935a-6392-42ca-b5cf-3ec685b866d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjUzMDgsIm5iZiI6MTcxNTQyNTAwOCwicGF0aCI6Ii8yODE4MzQ2OC8zMjk3NzU4OTAtNjEwNzkzNWEtNjM5Mi00MmNhLWI1Y2YtM2VjNjg1Yjg2NmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEwNTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNDAzNjNjMjcyN2NmOTI1MTMxZGI1NGM0NGE5MGZkZTYzOTBlMWQ1MjIyZmVmZTlmMDI3NzA0NWY4ZGRiOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ajZHRF2sD41VelBYLGnsHa-0EPQdETX-_8RVeyjdBRI">

I noticed this is with v1.0.3. The patch above should solves this. Do you know how to patch a package, may be?

**Comment by MaxAst** [comment]
@rranjan14's patch works for me, thank you! Would be great to get this fixed in @react-native-menu/menu

**Comment by NiharR27** [comment]
+ 1 getting those too.
With React native 0.74.1 and current latest version of the package `"@react-native-menu/menu": "^1.1.0",`. Will try and see if the patch works 🤞🏽

**Comment by JuanRdBO** [comment]
Now it works for me on the old arch, but new arch fails with the same error

<img width="573" alt="Screenshot 2024-07-09 at 09 14 55" src="https://github.com/react-native-menu/menu/assets/28183468/23d20b14-7eb9-4add-a06c-2a57f3a9731b">

**Comment by NadimRadjab** [comment]
Bumping react-native-menu to 1.1.2 solved the issue for me.
