### ISSUE TITLE
Support for testID

### ISSUE THREAD

**Issue by benjaminkomen** [react-native-menu/menu#817]
In my e2e (Maestro) tests we try to target testIDs instead of raw strings when clicking on things. It seems this MenuView component does not support a `testID` prop, unlike most React Native elements which do. Would it be possible to add support for this?

**Comment by mateoguzmana** [comment]
Support for `testID` has been added via #931. Available now in [v1.1.4](https://github.com/react-native-menu/menu/releases/tag/v1.1.4)

**Comment by benjaminkomen** [comment]
Thanks!
