### ISSUE TITLE
Long press support

### ISSUE THREAD

**Issue by mcchrish** [react-native-menu/menu#90]
Instead of press.

Is it possible?

**Comment by mcchrish** [comment]
Ok, I was thinking about the Context Menu functionality in iOS where the user long press an item and a menu pops up: https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/

There is already another library that does implements it that also use UIMenu: https://github.com/mpiannucci/react-native-context-menu-view. I do wonder though if this library can or will support it regardless.

**Comment by JoniVR** [comment]
I agree, the long press and pop from a certain item/preview would make this library absolutely perfect. Right now it's already pretty perfect, just not absolutely 😄 

Long press alone wouldn't add that much value imo (well, for me at least), I'm just trying to create user experiences that are as close to native as possible, this would make that possible.

**Comment by mihbel** [comment]
Hello! Is there any hope that the proposed PR will be merged?
